### ISSUE TITLE
Modal error message (when trying to swap amount = 0) - reported by Susanne

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#13]
name: Susanne
phone: 910777937
email: [susanne@impactmarket.com](mailto:susanne@impactmarket.com)
address: 0x06677920912dFa402F6400Afb4c16b8347fe2a17
role: Community Manager| gerente de comunidad| gestionnaire de communauté| gestor de comunidade
issue: Libera
issue2: Swap

1 - Modal error message (when trying to swap amount = 0): displaying "code" and not copy
2 - Trying to swap assets that I don't have (cEUR, for example): should display an error message, but only the button to proceed wasn't enabled

![Screenshot_20230315_174432_Libera](https://user-images.githubusercontent.com/127307303/226340215-30b721d6-936f-4673-90c0-619816f33bf3.jpg)
![Screenshot_20230315_174548_Libera](https://user-images.githubusercontent.com/127307303/226340219-fedfe451-ee4e-4954-8a7c-10a8ffe5861f.jpg)

**Comment by Marianavpt** [comment]
Didn't understand sorry. Do you want me to assign this issue (Trying to swap assets that I don't have (cEUR, for example): should display an error message, but only the button to proceed wasn't enabled) to Afonso, is that it?

**Comment by vibern0** [comment]
What I mean is, this can be handled in many different ways, so I'd prefer Afonso to say how. Otherwise likely he will want to change whatever we decide to do.

**Comment by Marianavpt** [comment]
What is your thought on this topic, @0xAf0n5o?
