### ISSUE TITLE
dApp: L&E- wrong ordering 

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#17]
Lesson number 7 is placed on the first place - Reported by Afonso

![IMG_0605](https://user-images.githubusercontent.com/127307303/226989777-1ba63ebf-ccee-4ff2-a355-2579fa6a091e.png)

**Comment by vibern0** [comment]
I see it ordered, but he has 5 lessons done, and I don't have any. We need more people to test and try to find this.

**Comment by Marianavpt** [comment]
I am seeing it in the correct order too, just tried now

**Comment by Marianavpt** [comment]
Correct order: 

![File (6)](https://user-images.githubusercontent.com/127307303/228263888-f43f4d3b-60b8-4124-8327-245dd70bff60.jpg)
![File (7)](https://user-images.githubusercontent.com/127307303/228263902-b70f2228-e5f0-4dc5-99e1-40601ec8b86a.jpg)
