### ISSUE TITLE
dApp: Settings - not able to change from Portuguese to English using Android (Libera and Metamask)

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#24]
- When in the dApp settings, trying to change from Portuguese to English, I have the notification (screenshot attached) that I need to sign the transaction in my wallet, but nothing appears on Metamask or Libera and the language doesn't change (keeps in PT)

- This is happening both in web and mobile 

![PWA - Not able to change the language](https://user-images.githubusercontent.com/127307303/229166481-18dbbb5c-4840-474d-b020-fc20cdfd7293.png)

**Comment by Marianavpt** [comment]
I've tested yesterday and today with iOS and it's working well

**Comment by vibern0** [comment]
It could have been a browser problem.
And yes, the first time, you need to validate your identity on the wallet.
Can this be closed then?

**Comment by Marianavpt** [comment]
@obernardovieira I can do it with no problem, but who reported, in this case Susanne, still can't using an android device. Can you recommend additional steps to help her?

**Comment by vibern0** [comment]
No idea

* Reconnect wallet (I assume she did)
* Change browser

She can also change language in Libera and the change will reflect on the webapp (if she is using the same account of course)
