### ISSUE TITLE
Libera: Donation - receiving and sending money with an error message (Urgent)

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#25]
name: Prof.Christiane Mendes
phone: +5598986059013
email: mendeschris33@gmail.com
address: 0xa41261d4ad48104aa9c3f81c2e3e4d7fd0a6f160
issue: Libera

1. Não consigo enviar doação pra comunidade, recebi uma doação em cUSD mas não conseguimos enviar p comunidade pela plataforma 
2. Não consigo solicitar fundos para comunidade sem aparecer msg de erro
3. Conseguimos doações de fundos e o doador não consegue enviar os fundos aparece msg de erro ao enviar
4. Os beneficiários não conseguem abrir o Libera, quando conseguem não têm fundos, alguns a tela só carrega o app sai e tem que começar tudo novamente. São pessoas simples só querem receber sua ubi sem  problemas.

A comunidade está insatisfeita, estamos perdendo credibilidade. Gostaria que algo fosse resolvido com urgência.

Não consigo subir o print na msg no suporte, ela sai da tela e não completa, depois de muitas tentativas espero que essa vá. Não consigo enviar msg p suporte sem sair pq os dados não ficam salvos, se sair da página para copiar um dado da carteira quando volta perde tudo que foi digitado

**Comment by vibern0** [comment]
This is quite vague. The same as saying, "nothing is working". That address does have activity. Unless reported more, this is an isolated case. Unstable internet could be one of the reasons. These are things we are working to improve.
