### ISSUE TITLE
Libera: Unable to add beneficiary to my new community

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#26]
name: Gracefield Godwin
phone: [+2349061401423](tel:+2349061401423)
email: [gracefield179@gmail.com](mailto:gracefield179@gmail.com)
role: Community Manager| Gerente de comunidad| Gestionnaire de communauté| Gestor de comunidade

Finding it difficult to add beneficiary to my new community and I do have a few CUSD in my wallet. the beneficiary account was  created with Libera

![IMG_20230328_183205_982](https://user-images.githubusercontent.com/127307303/229811632-794b8f85-ea4d-4976-bb6f-d3b478c77c52.jpg)

**Comment by vibern0** [comment]
using the email, I've got to the community. Seems to not be the problem.
Picking the address with OCR from the image seems to not be a problem either.
Looking at [sentry](https://impactmarket.sentry.io/issues/4072852079/?environment=production&project=6171011&query=is%3Aunresolved+user_activity%3Aadd_beneficiary&referrer=issue-stream&statsPeriod=14d&stream_index=0), I found that there has been some issue with some user, likely this user. This error is coming from _utils_ lib, and it basically says that the connection is broken.
This user should try to reconnect. We could also improve this error @hugomarquesdev. What do you think?

**Comment by Marianavpt** [comment]
Kingsley report the same issue of a Community Manager of Jahi Community that can't add beneficiaries - Keeps saying "User not Found"

![IMG_20230508_162529_575](https://github.com/impactMarket/support-issues/assets/127307303/ce4aedee-5663-46ba-9f30-fffbfb71338b)

**Comment by Marianavpt** [comment]
@obernardovieira do you know why this is happening?

**Comment by Marianavpt** [comment]
@Bernardo, Kingsley is still reporting the same error: cannot add or remove beneficiaries to existing or new communities. Any thoughts on this?

**Comment by vibern0** [comment]
This has been resolved.
