### ISSUE TITLE
dApp: Bug or Improvement: can´t edit communities parameters before generate the community to approval

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#29]
As an ambassador or a council member, i can´t edit communities parameters (claim amount; total amount, etc) before generate the community to approval. Just after generate and approve the community, i can change parameters that will need to be voted.
So, i think before generate the community should be possible to edit the parameters of amounts and not just description and image.

Don't know if this is a bug or an improvement - reported by Catarina

**Comment by Marianavpt** [comment]
@obernardovieira can you please confirm me if this is a bug or improvement? thanks!!!

**Comment by vibern0** [comment]
It is possible for an ambassador to edit parameters before generating a proposal. Please, see with @hugomarquesdev

**Comment by Marianavpt** [comment]
@hugomarquesdev can you please assist me here? Catarina told me is not working as it is

**Comment by Marianavpt** [comment]
@obernardovieira and @hugomarquesdev, Already confirmed with Catarina what is happening:
- it is possible to edit / correct the parameters from the Contract Details after "Generate proposal"
- but not before the proposal is generated, meaning: it's only available to edit the image and the description of the community, not the contract details (not even show up)

![Screenshot 2023-04-14 155444](https://user-images.githubusercontent.com/127307303/232080702-e27c3e32-9c57-436c-8d3d-466c46163578.png)
![Screenshot 2023-04-14 155407](https://user-images.githubusercontent.com/127307303/232080708-967a40a4-3e59-407b-b183-bf1f4239d55a.png)

**Comment by vibern0** [comment]
It is possible after and before the proposal. Before the proposal, only the ambassador who claimed it can change it. After the proposal, only the council. I've confirmed it.
