### ISSUE TITLE
Libera: Can´t send $PACT to other Libera wallet..it says i don´t have enough balance but is not true

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#31]
name: Catarina Neves
phone: 910408753
address: 0x091033aDC7fBdd4a1109c938585bfB54d0Fcf051

I can´t send $PACT to other Libera wallet..it says i don´t have enough balance but is not true

https://user-images.githubusercontent.com/127307303/230399444-cd3642fc-4738-4aa3-9e83-b184b95a280c.mp4

**Comment by Marianavpt** [comment]
@hugomarquesdev este issue pode estar relacionado com o PR web handling ou nada a ver?

**Comment by hugomarquesdev** [comment]
@Marianavpt é separado. isto é tudo na wallet

**Comment by vibern0** [comment]
I confirm.
This has been fixed although, [here](https://github.com/impactMarket/libera/pull/359/commits/f2caa7837d065391f93100c0e42cf560bca79566). Next Libera version will include this fix.
