### ISSUE TITLE
URGENT!! dApp: Not able to disconnect and not able to fill the support form and press send

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#36]
Using dApp though Libera I can´t disconnect because is showing the menus of Libera and I can´t reach the menu (Android - check video)
And using the cellphone - accessing dApp through Libera i can´t fill in the contact form if i press the chat button..is always disappearing
the menus and i need to fill in without seeing (maybe because of these  people said they can´t contact)  --- reported by Catarina

https://user-images.githubusercontent.com/127307303/232449562-7c5e7bea-ac2c-4325-a394-a41d866891df.mp4

**Comment by vibern0** [comment]
One duplicates this https://github.com/impactMarket/support-issues/issues/35 and the other is outside our control. See with LiveAgent support what they say.

**Comment by Marianavpt** [comment]
I was not able do disconnect before and now I am simply not able to Connect again
