### ISSUE TITLE
DF: Not able to donate through the impact Farming on the website reported by Susanne 

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#39]
Not being able to donate through the impact Farming on the website. Disconnected and connected the wallet, cleared website cookies, checked if there was any notification on Libera and nothing happens...it keeps loading forever in the Approve step

![Screenshot_20230419_172741_Samsung Internet_2](https://user-images.githubusercontent.com/127307303/233414533-3846db11-8e43-4184-b021-ae5dbab84061.jpg)

**Comment by Marianavpt** [comment]
The problem still exists today. Not on the PC but on the mobile phone (Android) yes and using different browsers and cleaning chache

**Comment by vibern0** [comment]
I haven't heard about this in a while, so, closing it for now.
