### ISSUE TITLE
Libera: When changing the Language on the Settings, the bar menu does not automatically assume that change

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#47]
![image](https://github.com/impactMarket/support-issues/assets/127307303/088d5ca6-fa87-4fad-a612-fe6a9670ab4e)

**Comment by Marianavpt** [comment]
any update on this issue @obernardovieira ?

**Comment by vibern0** [comment]
fixed in https://github.com/impactMarket/libera/pull/392
available on next version
