### ISSUE TITLE
Libera: Unable to collect PACT on Airdrop (iOS) - reported by Juan on behalf of beneficiary 

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#49]
![image](https://github.com/impactMarket/support-issues/assets/127307303/b28edcae-13ff-4c57-b8ae-b3db84f97080)

**Comment by Marianavpt** [comment]
@obernardovieira is this fixed?

**Comment by vibern0** [comment]
this as been fixed
