### ISSUE TITLE
Libera - Message after Staking: reported by Afonso

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#5]
After staking a message saying "you have staked all your PACT". There is no way to refresh this page so I have to close the app to see more PACT to refresh.

![IMG_0575](https://user-images.githubusercontent.com/127307303/225595177-67844835-6f7e-411d-8700-cf5c9239e1e7.PNG)

**Comment by obernardovieira** [comment]
Not sure I understood. After staking, it's all staked. New PACTs to stake only on the next epoch.

**Comment by Marianavpt** [comment]
@0xAf0n5o please. thanks
