### ISSUE TITLE
Swap is not working in Brazil - since yesterday (people can't take out their loans to use it)

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#55]
Swap is not working in Brazil - since yesterday (people can't take out their loans to use it) - reported by Catarina 

![image](https://github.com/impactMarket/support-issues/assets/127307303/237cd6a8-a0c1-4555-a777-26409a0df3c5)

![image](https://github.com/impactMarket/support-issues/assets/127307303/e71ede6c-bcd9-4199-90fe-6bc6eef14e36)

**Comment by Marianavpt** [comment]
@obernardovieira I believe this is Priority High

**Comment by vibern0** [comment]
this as been fixed
