### ISSUE TITLE
Unable to claim the loan after signing the contract  (Brazil) - reported by Catarina

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#56]
The borrower can´t claim her loan. They sign the contract, and when try to approve, it shows the error (see image). They did all procedures (clear cache; clear sessions), but still doesn´t work. The wallet has cUSD.

She doesn´t log off because when she press to get the recovery key it doesn´t give the words. 

I am sending a image of the cellphone model (android 11)

![WhatsApp Image 2023-07-11 at 13 43 02](https://github.com/impactMarket/support-issues/assets/127307303/2104f982-2e9e-42a5-a862-53cfde3a5a7d)

![WhatsApp Image 2023-07-11 at 13 48 55](https://github.com/impactMarket/support-issues/assets/127307303/b9558065-6216-4349-a3b2-d1b4a85bdaf6)

**Comment by Marianavpt** [comment]
@obernardovieira do you think this is the same issue as reported today by Jessica?

**Comment by vibern0** [comment]
I haven't heard about this in a while, so, closing it for now.
